### ISSUE TITLE
ArrayIndexOutOfBoundsException when trying to configure javaagent

### ISSUE THREAD

**Issue by bakrimoharram** [RayGicEFL/jb-netfilter#1]
when trying to run `java -jar jb-netfilter.jar` an ArrayIndexOutOfBoundsException exception thrown.

**Comment by RayGicEFL** [comment]
fixed in v3.0.1

**Comment by bakrimoharram** [comment]
thank you for the quick response.

**Comment by RayGicEFL** [comment]
thank you too for your support of this project（经典商业互夸了属于是（狗头

**Comment by RayGicEFL** [comment]
就玄学啊……  
刚刚加完新功能编译一次，发现又双叒叕 ArrayIndexOutOfBoundsException  
但是  
提交commit的时候刚测试过 不会抛出这个异常  
离谱。。人生中第一次 close掉别人的issue之后 自己又reopen 太神奇了。。  
判定是这样的：  
```java
    String arg = null;
    if (null != args) {
        arg = args[0];
    }
```  
也就是说，当传入main函数参数不为`null`时才会尝试获取args的第一个值  
所以问题所在就是 纵使我不传入参数 args的默认值也不是null  
然而args是数组，我不能使用isEmpty()方法  
这个问题等着明天修复吧 累了（

**Comment by RayGicEFL** [comment]
好吧……貌似可以试试`0 != args.length`的判定

**Comment by RayGicEFL** [comment]
没事了
